// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/about-me": {
            "get": {
                "description": "Возвращает данные о студенте (JSON или HTML)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "about-me"
                ],
                "summary": "Информация обо мне",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.About"
                        }
                    }
                }
            }
        },
        "/api/why-go": {
            "get": {
                "description": "Мотивация изучения Go",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "why-go"
                ],
                "summary": "Почему Go",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.Why"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.About": {
            "type": "object",
            "properties": {
                "last_name": {
                    "type": "string",
                    "x-order": "1"
                },
                "first_name": {
                    "type": "string",
                    "x-order": "2"
                },
                "middle_name": {
                    "type": "string",
                    "x-order": "3"
                },
                "university": {
                    "type": "string",
                    "x-order": "4"
                },
                "class": {
                    "type": "integer",
                    "x-order": "5"
                },
                "hobbies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "x-order": "6"
                }
            }
        },
        "main.Why": {
            "type": "object",
            "properties": {
                "fromCPlus": {
                    "type": "string"
                },
                "fromPython": {
                    "type": "string"
                },
                "universal": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MyServer API",
	Description:      "Учебный проект: API с информацией обо мне и о причинах изучения Go.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
